# NumPy Exercises 



#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [10]:
x=np.zeros(10)
y=np.array([0,0,0,0,0,0,0,0,0,0])
x,y

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

#### Create an array of 10 ones

In [18]:
a1=np.ones((1,10))
a2=np.ones(10)
a2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [20]:
a3=np.ones(10)
a3*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [33]:
a4=np.arange(10,51)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [34]:
a4[a4%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [37]:
a5=np.arange(0,9)
a5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [40]:
a6=np.identity(3)
a6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [43]:
np.random.rand(2)

array([0.4516516 , 0.97730422])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [44]:
np.random.randn(5,5)

array([[-0.80420276, -1.7777884 ,  0.97260505,  0.60178265, -0.8525136 ],
       [ 1.56676951,  0.49304813, -1.16621075,  0.22857065, -1.38178711],
       [ 1.24330799,  0.55349485,  0.78305573, -0.77144133, -1.82165627],
       [ 1.43516306,  0.92202581,  0.61918276, -1.35023789, -1.35944116],
       [-0.97768914,  1.00558403,  0.2913065 , -0.76605195,  0.93980779]])

#### Create the following matrix:

In [62]:
x=np.linspace(0.01,1.01,100)
x.reshape(10,10)

array([[0.01      , 0.02010101, 0.03020202, 0.04030303, 0.05040404,
        0.06050505, 0.07060606, 0.08070707, 0.09080808, 0.10090909],
       [0.1110101 , 0.12111111, 0.13121212, 0.14131313, 0.15141414,
        0.16151515, 0.17161616, 0.18171717, 0.19181818, 0.20191919],
       [0.2120202 , 0.22212121, 0.23222222, 0.24232323, 0.25242424,
        0.26252525, 0.27262626, 0.28272727, 0.29282828, 0.30292929],
       [0.3130303 , 0.32313131, 0.33323232, 0.34333333, 0.35343434,
        0.36353535, 0.37363636, 0.38373737, 0.39383838, 0.40393939],
       [0.4140404 , 0.42414141, 0.43424242, 0.44434343, 0.45444444,
        0.46454545, 0.47464646, 0.48474747, 0.49484848, 0.50494949],
       [0.51505051, 0.52515152, 0.53525253, 0.54535354, 0.55545455,
        0.56555556, 0.57565657, 0.58575758, 0.59585859, 0.6059596 ],
       [0.61606061, 0.62616162, 0.63626263, 0.64636364, 0.65646465,
        0.66656566, 0.67666667, 0.68676768, 0.69686869, 0.7069697 ],
       [0.71707071, 0.72717172, 0.7372727

#### Create an array of 20 linearly spaced points between 0 and 1:

In [56]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [65]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [67]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [68]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [69]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3,4]

20

In [70]:
mat[3,4]

20

In [80]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.vstack(mat[:3,1])

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [81]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [86]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [88]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [90]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [99]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!